// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudCurrencyInt s_hint = new CloudCurrencyInt("Hint", 3, false);

        public static int Hint
        {
            get { return s_hint.Value; }
            set { s_hint.Value = value; }
        }

        private static readonly CloudInt s_lastColor = new CloudInt("LastColor", PersistenceType.Latest, 0);

        public static int LastColor
        {
            get { return s_lastColor.Value; }
            set { s_lastColor.Value = value; }
        }

        private static readonly CloudInt s_lastAlphabet = new CloudInt("LastAlphabet", PersistenceType.Latest, 0);

        public static int LastAlphabet
        {
            get { return s_lastAlphabet.Value; }
            set { s_lastAlphabet.Value = value; }
        }

        private static readonly CloudInt s_lastMap = new CloudInt("LastMap", PersistenceType.Latest, 0);

        public static int LastMap
        {
            get { return s_lastMap.Value; }
            set { s_lastMap.Value = value; }
        }

        private static readonly CloudDateTime s_rewardsLastDateTime = new CloudDateTime("RewardsLastDateTime", PersistenceType.Latest);

        public static System.DateTime RewardsLastDateTime
        {
            get { return s_rewardsLastDateTime.Value; }
            set { s_rewardsLastDateTime.Value = value; }
        }

        private static readonly CloudInt s_rewardsDayCount = new CloudInt("RewardsDayCount", PersistenceType.Latest, 0);

        public static int RewardsDayCount
        {
            get { return s_rewardsDayCount.Value; }
            set { s_rewardsDayCount.Value = value; }
        }

        private static readonly CloudBool s_removeAds = new CloudBool("RemoveAds", PersistenceType.Highest, false);

        public static bool RemoveAds
        {
            get { return s_removeAds.Value; }
            set { s_removeAds.Value = value; }
        }

        private static readonly CloudBool s_unlockAllLevels = new CloudBool("UnlockAllLevels", PersistenceType.Highest, false);

        public static bool UnlockAllLevels
        {
            get { return s_unlockAllLevels.Value; }
            set { s_unlockAllLevels.Value = value; }
        }

        private static readonly CloudBool s_blockMetalAUnlocked = new CloudBool("BlockMetalAUnlocked", PersistenceType.Highest, false);

        public static bool BlockMetalAUnlocked
        {
            get { return s_blockMetalAUnlocked.Value; }
            set { s_blockMetalAUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockMetalBUnlocked = new CloudBool("BlockMetalBUnlocked", PersistenceType.Highest, false);

        public static bool BlockMetalBUnlocked
        {
            get { return s_blockMetalBUnlocked.Value; }
            set { s_blockMetalBUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockWoodAUnlocked = new CloudBool("BlockWoodAUnlocked", PersistenceType.Highest, false);

        public static bool BlockWoodAUnlocked
        {
            get { return s_blockWoodAUnlocked.Value; }
            set { s_blockWoodAUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockWoodBUnlocked = new CloudBool("BlockWoodBUnlocked", PersistenceType.Highest, false);

        public static bool BlockWoodBUnlocked
        {
            get { return s_blockWoodBUnlocked.Value; }
            set { s_blockWoodBUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockGreenMarbleUnlocked = new CloudBool("BlockGreenMarbleUnlocked", PersistenceType.Highest, false);

        public static bool BlockGreenMarbleUnlocked
        {
            get { return s_blockGreenMarbleUnlocked.Value; }
            set { s_blockGreenMarbleUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockBlueMarbleUnlocked = new CloudBool("BlockBlueMarbleUnlocked", PersistenceType.Highest, false);

        public static bool BlockBlueMarbleUnlocked
        {
            get { return s_blockBlueMarbleUnlocked.Value; }
            set { s_blockBlueMarbleUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockRedMarbleUnlocked = new CloudBool("BlockRedMarbleUnlocked", PersistenceType.Highest, false);

        public static bool BlockRedMarbleUnlocked
        {
            get { return s_blockRedMarbleUnlocked.Value; }
            set { s_blockRedMarbleUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockPurpleMarbleUnlocked = new CloudBool("BlockPurpleMarbleUnlocked", PersistenceType.Highest, false);

        public static bool BlockPurpleMarbleUnlocked
        {
            get { return s_blockPurpleMarbleUnlocked.Value; }
            set { s_blockPurpleMarbleUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockTileAUnlocked = new CloudBool("BlockTileAUnlocked", PersistenceType.Highest, false);

        public static bool BlockTileAUnlocked
        {
            get { return s_blockTileAUnlocked.Value; }
            set { s_blockTileAUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockTileBUnlocked = new CloudBool("BlockTileBUnlocked", PersistenceType.Highest, false);

        public static bool BlockTileBUnlocked
        {
            get { return s_blockTileBUnlocked.Value; }
            set { s_blockTileBUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockTileCUnlocked = new CloudBool("BlockTileCUnlocked", PersistenceType.Highest, false);

        public static bool BlockTileCUnlocked
        {
            get { return s_blockTileCUnlocked.Value; }
            set { s_blockTileCUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockTileDUnlocked = new CloudBool("BlockTileDUnlocked", PersistenceType.Highest, false);

        public static bool BlockTileDUnlocked
        {
            get { return s_blockTileDUnlocked.Value; }
            set { s_blockTileDUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockEmbroideryUnlocked = new CloudBool("BlockEmbroideryUnlocked", PersistenceType.Highest, false);

        public static bool BlockEmbroideryUnlocked
        {
            get { return s_blockEmbroideryUnlocked.Value; }
            set { s_blockEmbroideryUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockFootprintUnlocked = new CloudBool("BlockFootprintUnlocked", PersistenceType.Highest, false);

        public static bool BlockFootprintUnlocked
        {
            get { return s_blockFootprintUnlocked.Value; }
            set { s_blockFootprintUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockWaffleUnlocked = new CloudBool("BlockWaffleUnlocked", PersistenceType.Highest, false);

        public static bool BlockWaffleUnlocked
        {
            get { return s_blockWaffleUnlocked.Value; }
            set { s_blockWaffleUnlocked.Value = value; }
        }

        private static readonly CloudBool s_blockLatteUnlocked = new CloudBool("BlockLatteUnlocked", PersistenceType.Highest, false);

        public static bool BlockLatteUnlocked
        {
            get { return s_blockLatteUnlocked.Value; }
            set { s_blockLatteUnlocked.Value = value; }
        }
    }
}
