// <copyright file="CloudVariables.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using CloudPrefs;

    /// <summary>
    /// Provides access to cloud variables registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class CloudVariables
    {
        private static readonly CloudCurrencyInt s_hint = new CloudCurrencyInt("Hint", 3, false);

        public static int Hint
        {
            get { return s_hint.Value; }
            set { s_hint.Value = value; }
        }

        private static readonly CloudInt s_lastColor = new CloudInt("LastColor", PersistenceType.Latest, 0);

        public static int LastColor
        {
            get { return s_lastColor.Value; }
            set { s_lastColor.Value = value; }
        }

        private static readonly CloudInt s_lastAlphabet = new CloudInt("LastAlphabet", PersistenceType.Latest, 0);

        public static int LastAlphabet
        {
            get { return s_lastAlphabet.Value; }
            set { s_lastAlphabet.Value = value; }
        }

        private static readonly CloudInt s_lastMap = new CloudInt("LastMap", PersistenceType.Latest, 0);

        public static int LastMap
        {
            get { return s_lastMap.Value; }
            set { s_lastMap.Value = value; }
        }

        private static readonly CloudDateTime s_rewardsLastDateTime = new CloudDateTime("RewardsLastDateTime", PersistenceType.Latest);

        public static System.DateTime RewardsLastDateTime
        {
            get { return s_rewardsLastDateTime.Value; }
            set { s_rewardsLastDateTime.Value = value; }
        }

        private static readonly CloudInt s_rewardsDayCount = new CloudInt("RewardsDayCount", PersistenceType.Latest, 0);

        public static int RewardsDayCount
        {
            get { return s_rewardsDayCount.Value; }
            set { s_rewardsDayCount.Value = value; }
        }
    }
}
